# Generated by Django 3.2.5 on 2022-04-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=100000000000000000000000000000000000000000)),
                ('image', models.URLField()),
                ('category', models.CharField(choices=[('Miscellaneous', 'Miscellaneous'), ('Movies and Television', 'Movies and Television'), ('Sports', 'Sports'), ('Arts and Crafts', 'Arts and Crafts'), ('Clothing', 'Clothing'), ('Books', 'Books')], default=None, max_length=64)),
            ],
        ),
    ]
