# Generated by Django 3.2.5 on 2022-04-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=1000000000000),
        ),
    ]
