# Generated by Django 3.2.5 on 2022-05-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_comments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
    ]
