# Generated by Django 3.2.5 on 2022-05-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listings_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='user',
        ),
    ]
