# Generated by Django 3.2.5 on 2022-05-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='add_to_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
