# Generated by Django 3.2.5 on 2022-05-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_closelisting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closelisting',
            old_name='listing',
            new_name='listings',
        ),
    ]
