# Generated by Django 3.2.5 on 2022-06-09 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_rename_listing_watchlist_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='add_to_watchlist',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='listings',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auctions.listings'),
        ),
    ]
